install! 'cocoapods', :deterministic_uuids => false
platform :ios, '12.0'
project 'DeallocTestsAppCocoapods.xcodeproj'
use_frameworks!
inhibit_all_warnings!

target 'DeallocTestsAppCocoapodsTests' do
  pod 'DeallocTests', :path=>'../../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
