//
//  LeakHints.swift
//  DeallocTests
//
//  Copyright © 2026 STRV. All rights reserved.
//

import Foundation

/// Looks at the stored properties of a leaked object and points at the usual suspects.
///
/// `Mirror` can't tell weak properties from strong ones and can't look inside closures,
/// so the hints are suggestions, not proof.
enum LeakHints {
    /// How deep to look for reference cycles that go through properties
    static let maximumCycleDepth = 4
    /// Upper bound for visited objects, to keep huge object graphs fast
    static let maximumVisitedObjects = 300

    static func hints(for object: AnyObject) -> [String] {
        var hints = [String]()

        for property in storedProperties(of: object) {
            if let kind = suspiciousKind(of: property.value) {
                hints.append("`\(property.label)` is \(kind)")
            }
        }

        hints += cycles(from: object).map { path in
            "`\(path)` refers back to the object. That's a retain cycle unless one of the references is weak"
        }

        return hints
    }

    // MARK: - Suspicious properties

    private static func suspiciousKind(of value: Any) -> String? {
        let typeName = String(describing: type(of: value))

        if typeName.contains("->") {
            return "a closure. Make sure it captures self weakly"
        }

        if typeName.contains("AnyCancellable") {
            return "a Combine subscription. Make sure its sink captures self weakly"
        }

        if typeName.hasPrefix("Task<") || typeName.hasPrefix("Optional<Task<") {
            return "a task. Make sure it's cancelled or captures self weakly"
        }

        if typeName.contains("Timer") {
            return "a timer. A scheduled timer keeps its target until it's invalidated"
        }

        return nil
    }

    // MARK: - Cycles

    /// Paths through stored properties that lead back to the object
    private static func cycles(from root: AnyObject) -> [String] {
        let rootIdentifier = ObjectIdentifier(root)
        var visited: Set<ObjectIdentifier> = [rootIdentifier]
        var queue: [(object: AnyObject, path: String, depth: Int)] = [(root, "self", 0)]
        var found = [String]()

        while !queue.isEmpty, visited.count < maximumVisitedObjects {
            let (object, path, depth) = queue.removeFirst()

            guard depth < maximumCycleDepth else {
                continue
            }

            for property in storedProperties(of: object) {
                for child in referencedObjects(in: property.value) {
                    let childPath = "\(path).\(property.label)"
                    let childIdentifier = ObjectIdentifier(child)

                    if childIdentifier == rootIdentifier, depth > 0 {
                        found.append(childPath)
                    } else if isUserDefined(type(of: child)), visited.insert(childIdentifier).inserted {
                        queue.append((child, childPath, depth + 1))
                    }
                }
            }
        }

        return found
    }

    // MARK: - Reflection

    private struct Property {
        let label: String
        let value: Any
    }

    /// Stored properties of the object's own class and its user-defined superclasses
    private static func storedProperties(of object: AnyObject) -> [Property] {
        var properties = [Property]()
        var mirror: Mirror? = Mirror(reflecting: object)

        while let currentMirror = mirror {
            if let subjectType = currentMirror.subjectType as? AnyClass, !isUserDefined(subjectType) {
                break
            }

            for child in currentMirror.children {
                // `_$observationRegistrar` is generated by `@Observable`, not the app's state
                guard let label = child.label, !label.hasPrefix("_$") else {
                    continue
                }
                properties.append(Property(label: cleaned(label), value: child.value))
            }

            mirror = currentMirror.superclassMirror
        }

        return properties
    }

    /// Class instances stored directly or inside optionals, collections, tuples and structs
    private static func referencedObjects(in value: Any, depth: Int = 0) -> [AnyObject] {
        let mirror = Mirror(reflecting: value)

        if mirror.displayStyle == .class {
            return [value as AnyObject]
        }

        guard depth < 3 else {
            return []
        }

        return mirror.children.prefix(50).flatMap { referencedObjects(in: $0.value, depth: depth + 1) }
    }

    /// Skips Apple framework classes like `UIView`, so hints point at the app's own code
    private static func isUserDefined(_ objectClass: AnyClass) -> Bool {
        guard let bundleIdentifier = Bundle(for: objectClass).bundleIdentifier else {
            return true
        }
        return !bundleIdentifier.hasPrefix("com.apple.")
    }

    private static func cleaned(_ label: String) -> String {
        // Lazy properties are stored as `$__lazy_storage_$_name`
        let label = label.replacingOccurrences(of: "$__lazy_storage_$_", with: "")
        // `@Observable` stores each property as `_name`
        return label.hasPrefix("_") ? String(label.dropFirst()) : label
    }
}
